apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  PORT: "8082"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: content-engine-configmap
data:
  WELCOME_MSG: 'Welcome to content engine'