apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-engine-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-engine-deployment
  template:
    metadata:
      labels:
        app: content-engine-deployment
    spec:
      containers:
      - name: content-engine
        image: raidsulin/content-engine:latest
        env:
        - name: PORT
          value: "8082"  
        - name: WELCOME_MSG
          valueFrom:
            configMapKeyRef:
              name: content-engine-configmap
              key: WELCOME_MSG
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_BUCKET_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
