apiVersion: v1
kind: Service
metadata:
  name: content-engine-service
spec:
  selector:
    app: content-engine-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8082
  type: ClusterIP