# Generated by Django 4.2.16 on 2024-09-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['timestamp']},
        ),
    ]
