# Generated by Django 4.2.16 on 2024-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='handle',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
